name 'deployer'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures deployer'
long_description 'Installs/Configures deployer'
version '0.1.0'
